### PR TITLE
Removing .hgignore file and adding .gitignore file as we move this repository to git and github.

### PR DESCRIPTION
**Pull request by rzelayafavila**

### CODE REVIEW

**Comment by mhuyck** [comment]
Okay, I tested this one since I figured out it would be easy to just fork the repo... looks as if the lines starting after `syntax: glob` are respected (added a .pyc file and it was properly ignored) but the whole `syntax: regexp` section probably doesn't work with `git` (I added a `sqlite.db` file and it was not ignored).

There's probably a lot of old stuff that can get cleaned out of here, too. Are the `.sublime-project` and `.sublime-workspace` still relevant? If those files are specific to your editor they should probably be added to `$HOME/.config/git/ignore` rather than the project repo (that's where I have added `.DS_Store`, which is Mac-specific metadata, and `.tm_properties`, which has settings for my text editor).

**Comment by rzelayafavila** [comment]
Hi @mhuyck - yes, sorry, I jumped the gun and opened these before I headed out from work, but good call, I am going to make the necessary changes on all of these tomorrow when I get back to the lab.

**Comment by rzelayafavila** [comment]
Ok @mhuyck - I changed the syntax on the .gitignore files for this repo and the other ones, and also updated them, cleaning out files that shouldn't be there. I tested all of them and they seem to be working. Let me know how they look, thanks!

**Comment by mhuyck** [comment]
Nice. LGTM!

**Pull request merged**
