### PR TITLE
Modifying fabfile to use git instead of mercurial

### PR DESCRIPTION
**Pull request by rzelayafavila**
This PR is connected to https://github.com/greenelab/tribe-ec2-deploy/pull/2, where the location of the repository is changed to GitHub.

### CODE REVIEW

**Comment by rzelayafavila** [comment]
Ah, thanks @mhuyck and @dongbohu! I actually realized that I needed to make a change to the `_git_pull` function so that it would take 'master' by default instead of 'tip' (different from mercurial), and to specify that the name of a branch can also be passed. Please let me know how these look!

**Comment by mhuyck** [comment]
Ah, ok. I missed that, obviously! This looks good and if it's working well then probably shouldn't be changed. As you mentioned this morning, these are minimal changes to the Tribe deployment process, and that makes sense.

For what it's worth: I am not sure you actually need the `git checkout` step since `git pull` should cover your bases for you. You can specify the branch you want to `git pull` via the `refspec` parameter. See:

> https://git-scm.com/docs/git-pull

I tweaked the process for `adage-server` to avoid prompting so I could specify all of the deployment details in `config.py` and then have a `fab aws_deploy` script run everything in a fully automated way.

So, anyway: don't change any of this now, but the above might be helpful to know about down the road. (Or if you ever find yourself making changes to these steps on `adage-server`.)

**Comment by rzelayafavila** [comment]
Gotcha, thanks for the insight @mhuyck!

**Comment by rzelayafavila** [comment]
All set for looking at again!

**Comment by rzelayafavila** [comment]
Ok, thank you both again!

**Pull request merged**
